# Generated by Django 3.2 on 2021-04-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyusage',
            old_name='day',
            new_name='date',
        ),
    ]
