# Generated by Django 3.2 on 2021-04-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_video_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnails',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
